//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoodleManagerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public long id { get; set; }
        public string fullname { get; set; }
        public Nullable<long> categoryid { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
